name: Vulnerability scan

on: [push, pull_request]

jobs:
  vulnerabilities-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: debricked/actions/scan@v1
        env:
          USERNAME: ${{ secrets.DEBRICKED_USERNAME }}
          PASSWORD: ${{ secrets.DEBRICKED_PASSWORD }}
